stages:
  - test
  - sonar

variables:
  PYTHON_VERSION: "3.11"

test:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - python --version
  script:
    - pip install -r requirements.txt
    - python -m pytest tests/ --cov=src --cov-report=xml --cov-report=html --cov-report=term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: coverage.xml
  #   paths:
  #     - coverage.xml
  #     - htmlcov/
  #   expire_in: 1 week

sonar:
  stage: sonar
  image: python:${PYTHON_VERSION}
  script:
    - pip install pysonar
    - pysonar --sonar-host-url=$SONAR_HOST --sonar-token=$SONAR_PASSWORD  --sonar-project-key=demo-cicd-ihab --sonar-qualitygate-wait
  only:
    - main